### ISSUE TITLE
“slider” GUIControl needs dirty = true to update

### ISSUE THREAD

**Issue by yinshanyang** [pex-gl/pex-gui#2]
Hey Marcin, probably more of a documentation issue.

Was working off the audio.Audio example (https://github.com/vorg/pex-examples/blob/master/src/audio.Audio/main.js) and found that it was misleading as my variant only needed the progress slider and when everything else was stripped off, the slider stops updating.

Found that I needed to assign the slider, e.g.:

```
init: function() {
  …
  this.slider = this.gui.addParam('Progress', this, 'progress', { min: 0, max: 1}, this.onSeek.bind(this));
  …
}
```

And subsequently in the rendering cycle, declare that it is dirty:

```
draw: function() {
  …
  this.progress = this.audio.duration ? this.audio.currentTime / this.audio.duration : 0;
  this.slider.dirty = true;
  …
}
```

**Comment by vorg** [comment]
Yes, there is no better way to notify GUI that it needs to update at the moment. I'll reopen this to remember to add info in the documentation.

**Comment by dmnsgn** [comment]
`gui.draw()` should update the gui and remove any need for `.dirty` since it has been moved from the Renderer to the GUI (ef03f23df182e9e4c19984f3859b47be81cf90dd)
