### ISSUE TITLE
Default responsive to false

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-gui#41]
I find it more intuitive that gui is controlled with `scale`. Current `responsive:true` often causes gui to scale. `pixelRatio` seems to do nothing? What's the correct way to use those 3 params?

**Comment by dmnsgn** [comment]
## Responsive and scale
`responsive` is more than just convenience, it makes the GUI usable where before it would use to just overflow the viewport and makes some controls unusable.

If you manually specify the scale (and disable responsive), that means you don't intend to have it fit your screen at all time and that is only a good idea if you are sure the screen dimensions won't change and the GUI to occupy a specific amount of screen space.

What you are after is probably to be able to set the default scale to something smaller/bigger even with responsive? It would act as a global scale but also support responsive. Currently it is `1`:
https://github.com/pex-gl/pex-gui/blob/655cd0754f9e4813f25f1014ffa9bb68d32c4599/index.js#L1138-L1145 

If you have to do this every time though, it kind of implies the default of 1 is not right and for the sake of consistency it should be changed. 

## pixelRatio

Ideally, `pixelRatio` only controls how sharp it is drawn.

It is propagated to the renderer in the setter to control the scale `ctx.scale(this.pixelRatio, this.pixelRatio);` at which it is drawn: https://github.com/pex-gl/pex-gui/blob/655cd0754f9e4813f25f1014ffa9bb68d32c4599/index.js#L52-L55

Practically, there are some difference if you're using a context 2D or a pex-context (where it is inherited from the ctx.pixelRatio). There are probably a few bugs left as a result (#39).

**Comment by vorg** [comment]
I think my issue is that we have 3 settings while all i care is maybe 1 : scale.

Here is 4k content with default settings. Unusable.

![Screenshot 2022-09-06 at 12 51 48](https://user-images.githubusercontent.com/171001/188628099-36e00810-28ae-4cf4-a376-0d51069291d8.jpg)


setting scale to counteract how much "retina" the canvas is `gui.scale = ctx.gl.canvas.height / ctx.gl.canvas.clientHeight;` will create gui that is consistently the same on the screen despite canvas resolution

![Screenshot 2022-09-06 at 12 52 58](https://user-images.githubusercontent.com/171001/188628133-33c2d56a-e68c-4459-ba12-edefd0ca308c.jpg)

That could be default and automatic.  Now if i really want big fat gui for mobile i set scale to 2x and would get 

![Screenshot 2022-09-06 at 12 54 48](https://user-images.githubusercontent.com/171001/188628297-6f3442a6-48a2-4a55-ad4a-8f8799e0f21d.jpg)
